export const INDUSTRY_OPTIONS = [
  'Alat Pemadam Kebakaran',
  'Alat Perekat/Pelumas',
  'Alat Potong',
  'Alat Tekuk',
  'Alat Ukur',
  'ATK (Alat Tulis Kantor)',
  'Base Plate',
  'Baterai',
  'Boring Machining',
  'Brake Cleaner',
  'Brazing Flux',
  'Centrifugal Fan',
  'Certificate',
  'Circuit Beaker',
  'Coil Break',
  'Connecting Roller',
  'Cover',
  'Cylinder Head',
  'Digital Marketing',
  'Dynabolt',
  'Ekspedisi',
  'Elektrik motor',
  'Engine',
  'Flexibel Mechanical',
  'Freight Forwarder',
  'Gas',
  'Gearbox',
  'Insulator',
  'Jasa Alat Ukur',
  'Jasa Asuransi',
  'Jasa dan Alat Bahan Bangunan',
  'Jasa dan Spare Part Dinamo',
  'Jasa dan Spare Part Mobil-Motor',
  'Jasa dan Toko Komputer/Laptop',
  'Jasa Fabrikasi Material',
  'Jasa Instalasi',
  'Jasa Kalibrasi',
  'Jasa Sewa Crane',
  'Kompresor',
  'Kondensor',
  'Mesin',
  'Material Baja',
  'Material Baut dan Mur',
  'Material Bearing',
  'Material Belt',
  'Material Besi',
  'Material Elektrikal',
  'Material Filter',
  'Perlengkapan Alat Pelindung Diri',
  'Software',
  'Tools Gear',
  'V-Belt',
  'Versen Metal',
  'V-Ring',
  'V-Seal',
].map((label) => ({ label, value: label }));
